kernel-install: Support alternate root usage via SUBDIR/PLUGIN_SUBDIR

diff --git a/src/kernel-install/kernel-install b/src/kernel-install/kernel-install
--- a/src/kernel-install/kernel-install
+++ b/src/kernel-install/kernel-install
@@ -28,7 +28,10 @@ usage()
     echo "Options:"
     echo "  -h,--help     Print this help"
     echo "  -v,--verbose  Increase verbosity"
+    echo "  -p,--root     Optional. Prefix kernel-install operations with different root"
 }
+
+SUBDIR=""
 
 dropindirs_sort()
 {
@@ -58,12 +61,26 @@ dropindirs_sort()
 
 export LC_COLLATE=C
 
-for i in "$@"; do
-    if [ "$i" == "--help" -o "$i" == "-h" ]; then
+args=("$@")
+for ((i=0; i < $#; i++)) {
+    arg="${args[$i]}"
+    if [ "$arg" == "--help" -o "$arg" == "-h" ]; then
         usage
         exit 0
+    elif [ "$arg" == "--root" ]; then
+        if [[ "$((i+1))" -lt $# ]]; then
+            SUBDIR="${args[$((i+1))]}"
+            export SUBDIR
+        else
+            usage
+            exit 1
+        fi
     fi
-done
+}
+
+if [[ ! -z "${SUBDIR}" ]]; then
+    shift; shift;
+fi
 
 KERNEL_INSTALL_VERBOSE=0
 if [ "$1" == "--verbose" -o "$1" == "-v" ]; then
@@ -86,13 +103,22 @@ KERNEL_VERSION="$1"
 KERNEL_IMAGE="$2"
 
 # Reuse directory created without a machine ID present if it exists.
-if [[ -d /efi/Default ]] || [[ -d /boot/Default ]] || [[ -d /boot/efi/Default ]]; then
-    MACHINE_ID="Default"
-elif [[ -f /etc/machine-id ]]; then
-    read MACHINE_ID < /etc/machine-id
-else
-    MACHINE_ID="Default"
+if [[ -f "${SUBDIR}/etc/machine-id" ]]; then
+    read MACHINE_ID < "${SUBDIR}/etc/machine-id"
 fi
+
+if ! [[ $MACHINE_ID ]]; then
+    echo "Could not determine your machine ID from ${SUBDIR}/etc/machine-id." >&2
+    echo "Please run 'systemd-machine-id-setup' as root. See man:machine-id(5)" >&2
+    if [[ -z "${SUBDIR}" ]]; then
+        exit 1
+    else
+        # Enable bare-chroot usage.
+        BOOT_DIR_ABS="${SUBDIR}/boot"
+    fi
+else
+    BOOT_DIR_ABS="${SUBDIR}/boot/$MACHINE_ID/$KERNEL_VERSION"
+ fi
 
 if [[ ! $COMMAND ]] || [[ ! $KERNEL_VERSION ]]; then
     echo "Not enough arguments" >&2
@@ -119,8 +145,8 @@ ret=0
 
 readarray -t PLUGINS <<<"$(
     dropindirs_sort ".install" \
-        "/etc/kernel/install.d" \
-        "/usr/lib/kernel/install.d"
+        "${SUBDIR}/etc/kernel/install.d" \
+        "${SUBDIR}/usr/lib/kernel/install.d"
 )"
 
 case $COMMAND in
@@ -138,8 +164,8 @@ case $COMMAND in
         for f in "${PLUGINS[@]}"; do
             if [[ -x $f ]]; then
                 [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && \
-                    echo "+$f add $KERNEL_VERSION $ENTRY_DIR_ABS $KERNEL_IMAGE ${INITRD_OPTIONS[@]}"
-                "$f" add "$KERNEL_VERSION" "$ENTRY_DIR_ABS" "$KERNEL_IMAGE" "${INITRD_OPTIONS[@]}"
+                    echo "+PLUGIN_SUBDIR=${SUBDIR} $f add $KERNEL_VERSION $BOOT_DIR_ABS $KERNEL_IMAGE ${INITRD_OPTIONS[@]}"
+                PLUGIN_SUBDIR="${SUBDIR}" "$f" add "$KERNEL_VERSION" "$BOOT_DIR_ABS" "$KERNEL_IMAGE" "${INITRD_OPTIONS[@]}"
                 x=$?
                 if [[ $x == $SKIP_REMAINING ]]; then
                     ret=0
@@ -154,8 +180,8 @@ case $COMMAND in
         for f in "${PLUGINS[@]}"; do
             if [[ -x $f ]]; then
                 [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && \
-                    echo "+$f remove $KERNEL_VERSION $ENTRY_DIR_ABS"
-                "$f" remove "$KERNEL_VERSION" "$ENTRY_DIR_ABS"
+                    echo "+PLUGIN_SUBDIR={SUBDIR} $f remove $KERNEL_VERSION $ENTRY_DIR_ABS"
+                PLUGIN_SUBDIR="${SUBDIR}" "$f" remove "$KERNEL_VERSION" "$BOOT_DIR_ABS"
                 x=$?
                 if [[ $x == $SKIP_REMAINING ]]; then
                     ret=0
@@ -165,10 +191,12 @@ case $COMMAND in
             fi
         done
 
-        [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && \
-            echo "Removing $ENTRY_DIR_ABS"
 
-        rm -rf "$ENTRY_DIR_ABS"
+        if [[ -z "${SUBDIR}" ]]; then
+            [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && \
+                echo "Removing $ENTRY_DIR_ABS"
+            rm -rf "$BOOT_DIR_ABS"
+        fi
         ((ret+=$?))
         ;;
 
